### ISSUE TITLE
Unreachable landvoc domain if www is used

### ISSUE THREAD

**Issue by dayures** [landportal/drupal#487]
- `http://landvoc.org/` working
- `https://landvoc.org/` working
- `http://www.landvoc.org/` not working error 404
- `https://www.landvoc.org/` not working error 404

It looks like this is NOT the case for landportal.org

**Comment by asanchez75** [comment]
fixed. 
please, check and close it if you agree.

**Comment by dayures** [comment]
Thanks

The issue still applies to the rest of landvoc domains (.net, .com, .info)

**Comment by asanchez75** [comment]
fixed.
please, check and close it if you agree.
