### ISSUE TITLE
Maximum amount of topics to link to overarching categories

### ISSUE THREAD

**Issue by lisettemeij** [landportal/drupal#61]
There is a maximum amount of characters that can be linked to a 'domain' (which again: should be overarching category). Can we delete this maximum amount? I can't fill in all the fixed relationships this way.

**Comment by jcr** [comment]
Fixed for overarch/themes, overarch/topics, and themes/topics relations.
It is now a 'select synomym friendly' selection with autocomplete.

https://landportal.info/taxonomy/term/7340/edit?destination=admin/structure/taxonomy/domains

**Comment by lisettemeij** [comment]
Hi Jules, I still can't add more concepts. It's giving me the same error. I reached the maximum amount of characters (which is 1024)
